name: OpenSrc
on:
  workflow_dispatch:
jobs:
  opensrc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test.pl
        run: ./test.pl
      - name: Git Version
        run: git version
      - name: Perl Version
        run: perl -V
      - name: List folders
        run: ls -al
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
